# https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

php:
  - 5.4
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0

before_script:
  - composer self-update
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
